spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9999
        #namespace: bc7613d2-2e22-4292-a748-48b78170f14c  #指定namespace的id
  application:
    name: order-center
  main:
    allow-bean-definition-overriding: true

#指定FeignClientApi的日志级别

server:
  port: 8080
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'