spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: order-center
server:
  port: 8080
logging:
  level:
    com:
      loving: debug

#开启连接池配置
feign:
  client:
    config:
      product-center:
        loggerLevel: basic
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50