spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9999
        #namespace: bc7613d2-2e22-4292-a748-48b78170f14c  #指定namespace的id
  application:
    name: order-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
logging:
  level:
    com:
      loving: debug

#开启连接池配置
feign:
  client:
    config:
      product-center:
        loggerLevel: basic
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true