server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #namespace: bc7613d2-2e22-4292-a748-48b78170f14c  #Ö¸¶¨namespaceµÄid
  application:
    name: order-center
