server:
  port: 8888
spring:
  application:
    name: gateway-sentinel
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: product_center
        uri: lb://product-center
        predicates:
        - Path=/**
      - id: order_center
        uri: lb://order-center
        predicates:
        - Path=/**
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9999
  main:
    allow-bean-definition-overriding: true
