#说明请求http://localhost:8888/selectProductInfoById/1的
#Host必须满足www.smlz.com:8888或者localhost:8888才会
#转发到http://product-center/selectProductInfoById/1
spring:
  cloud:
    gateway:
      routes:
      - id: host-route #id必须要唯一
        uri: lb://product-center
        predicates:
        - Host=www.life.com:8888,localhost:8888
