spring:
  cloud:
    gateway:
      routes:
      - id: filterfacotory-route #id必须要唯一
        uri: lb://product-center
        predicates:
        - TimeBetween=上午7:00,下午11:00
        filters:
          #请求头添加信息
#        - AddRequestHeader=X-Request-Company,Bar
          #统计接口耗时
          - TimeMonitor=enabled,true