#当前请求的方式 http://localhost:8888/selectProductInfoById/1 是Post才会被转发
#到http://product-center/selectProductInfoById/1
spring:
  cloud:
    gateway:
      routes:
      - id: method-route #id必须要唯一
        uri: lb://product-center
        predicates:
        - Method=Post